### ISSUE TITLE
Important issue

### ISSUE THREAD

**Issue by notrhys** [StelGithub/Sonix#1]
stop skidding from others
https://github.com/DemonDxv/Anticheat-Open-Source

Sonix: (Banwaves)
![image](https://user-images.githubusercontent.com/40679762/215230017-1ca988c8-8c83-4cbe-bd1d-9f9d5f915e17.png)

Anticheat-Open-Source (Banwaves)
![image](https://user-images.githubusercontent.com/40679762/215230046-c4e51a6a-afaf-44ee-9720-4def04662afd.png)

Sonix: (Timer#A)
![image](https://user-images.githubusercontent.com/40679762/215230151-ef3fd8a2-297b-4fa4-810a-556c92b5b8cc.png)

Anticheat-Open-Source (Timer#A)
![image](https://user-images.githubusercontent.com/40679762/215230195-cb2bbb25-19c3-4377-91c2-77e020820dc0.png)

aka the entire anticheat
really funny

**Comment by StelGithub** [comment]
if you have checked any other class you would see there are credits, i don't have time to add credits to every class.

**Comment by ElectrumIsPog** [comment]
Then dont use the code?

**Comment by notrhys** [comment]
> if you have checked any other class you would see there are credits, i don't have time to add credits to every class.

Oh yeah?
![image](https://user-images.githubusercontent.com/40679762/215231005-ece07f4f-4df3-4b37-8c70-713d9549a271.png)
![image](https://user-images.githubusercontent.com/40679762/215231104-043bff66-cf6b-475f-8591-5bc10bff0da2.png)
![image](https://user-images.githubusercontent.com/40679762/215231201-3630526b-0bad-4a5f-bb8e-2d9e39aaca69.png)
![image](https://user-images.githubusercontent.com/40679762/215231271-a77192dc-ec45-4b25-a995-c03cf949f2ce.png)

i dont see any credits

**Comment by StelGithub** [comment]
FlyA, FlyC, etc.

**Comment by notrhys** [comment]
> FlyA, FlyC, etc.

ok wow you skidded someone elses checks.. now what about the checks you didn't give credit for?

**Comment by notrhys** [comment]
and the base

**Comment by StelGithub** [comment]
so when i add credits it's still skidding? you got serious mental issues.

**Comment by notrhys** [comment]
> so when i add credits it's still skidding? you got serious mental issues.

lets be honest, i highly doubt you can credit an anticheat without any help from anyone else, so yeah i guess it would be

**Comment by StelGithub** [comment]
cool story
